### ISSUE TITLE
牛B

### ISSUE THREAD

**Issue by yishenggudou** [ascoders/gaea-editor#1]
这个项目的支持度会怎样?

**Comment by ascoders** [comment]
正在研发和完善中，贴吧创新业务即将全面使用，而且会继续将核心编辑器开源

**Comment by ihtml5** [comment]
对这个组件可视化编辑器感兴趣，不知道怎么能跑起来这个项目

**Comment by yishenggudou** [comment]
@ascoders 投入人力情况 如何 要不要一起完善下

**Comment by ascoders** [comment]
http://next.baidu.com/components/editor/gaea-editor

这里有安装方式

```bash
npm install gaea-editor --save
```

用法看 demo 的『查看源码』

**Comment by ascoders** [comment]
@yishenggudou 我全职维护，另一部分精力在做组件平台，欢迎提 PR，有问题可以发在这里讨论。
