### ISSUE TITLE
关于基本组件下拉选项 select 不能拖拽

### ISSUE THREAD

**Issue by begoat** [ascoders/gaea-editor#10]
你好，发现 基本的默认组件 select 下拉选项 拖拽起来 有点问题，不方便直接拖拽他

然后昨天导了antd-mobile  的 Button组件之后 在 gaeaSetting 里面设置了 isPreview = true 之后 还是不可以。

antd-mobile 里面 Button 的 情况是 拖动1次 正常，然后就不能拖动了，
基本组件select  是 无论怎么样 都不方便拖拽

希望 大大解决下😊

**Comment by ascoders** [comment]
这个问题是冒泡顺序导致的。

拖拽响应在组件的最顶层，如果组件内部的点击被阻止冒泡了，顶层就监听不到组件被点击。

暂时没有想到更好的方法，你可以通过右侧菜单的树状图来拖拽，效果是一样的，而且不会存在不能拖动的问题。

**Comment by begoat** [comment]
嗯
