### ISSUE TITLE
如何绑定state里的值? 或者给按钮 加点击事件？

### ISSUE THREAD

**Issue by yjj5855** [ascoders/gaea-editor#12]
看了下demo 貌似没找到这么绑定的

**Comment by ascoders** [comment]
想要什么效果？说一下需求吧

**Comment by yjj5855** [comment]
比如我有个页面组件 我可以在页面组件里定义
```
getInitialState() {
    return {
        form: {
            name: ''
        }
    }
 }
```
然后再页面组件里加一个表单组件 里面一个input或select绑定这个`state.form.name`

**Comment by ascoders** [comment]
在 `gaea-editor` 添加组件，可以通过 `plugins` 方式拓展：

1. [写一个 store](https://github.com/ascoders/gaea-editor/blob/master/src/plugins/main-tool-tree/store.ts#L9)
2. [在插件中定义自己申明的 store](https://github.com/ascoders/gaea-editor/blob/master/src/plugins/main-tool-tree/index.tsx#L59)
3. [插件Connect](https://github.com/ascoders/gaea-editor/blob/master/src/plugins/main-tool-tree/index.tsx#L13) 可以注入所有编辑器已有的 store 和自己定义的 store。
4. [在插件的任何文件使用它](https://github.com/ascoders/gaea-editor/blob/master/src/plugins/main-tool-tree/guideline/guideline.component.tsx#L26)

**Comment by yjj5855** [comment]
大概知道怎么写了 谢谢
