### ISSUE TITLE
您能把文档完善么？感觉好简陋。

### ISSUE THREAD

**Issue by tyua07** [ascoders/gaea-editor#13]
如题，比如每一个 ``defaultProps`` 都有一个 ``gaeaName`` 属性，但是在您的简书上面的例子，还有一个 ``name`` 那么属性也需要设置，有什么区别么？

**Comment by ascoders** [comment]
简书上只是demo，与真实api不太一样，我会在这几天补充完善文档的😊。

**Comment by tyua07** [comment]
好的，非常感谢。另外说个需求，不知道支不支持。比如一个栅格系统，Row 组件里面只能插入 Col 组件，如果拖拽其他组件进去是非法的。在[grapesjs](https://github.com/artf/grapesjs/wiki/API-Components) 扩展组件的时候有2个属性 ``draggable`` 和 ``droppable`` 用来表示允许拖入到哪和允许什么拖入到自身。

**Comment by ascoders** [comment]
这个需求还不支持，但是可以支持。我可以调研一下 grapesjs 这个平台功能这么全了，为什么还要用 gaea-editor吗？

**Comment by tyua07** [comment]
他有一个组件的插件 [grapesjs-mjml](https://github.com/artf/grapesjs-mjml) ，你可以看下，感觉写起来很麻烦。应用到 react ，我觉得要写多余的很多东西。还推荐一个 [structor](https://github.com/ipselon/structor) ，这个要去修改也是很麻烦。

**Comment by ascoders** [comment]
周末加上文档

**Comment by tyua07** [comment]
好的！谢谢

**Comment by ascoders** [comment]
文档基本完成了

**Comment by tyua07** [comment]
好的
