### ISSUE TITLE
关于typescript导入到JavaScript项目中

### ISSUE THREAD

**Issue by tianqingfish** [ascoders/gaea-editor#15]
这个组件是typescript写的，我在插入进JavaScript项目的时候，会跳出
Uncaught (in promise) TypeError: Cannot read property 'object' of undefined错误

想请问下，是不是需要对webpack做出适配呢？
PS：我已经在项目的目录下安装好typescript了，也按照您说的安装好gaea-editor了（npm i gaea-editor）

**Comment by ascoders** [comment]
如果在项目安装好了 typescript，那就以 typescript 的方式引用。项目是 js 的还是 ts 的？

ts 对 js 项目是无感知的，对 ts 项目是类型增强的，应该没有影响。

**Comment by tianqingfish** [comment]
项目是Js的，我的想法是在antdesignPro新建一个页面，然后把gaea引用到新页面中，但是当我用npm安装好gaea后，只要import Gaea from 'Gaea-editor'，就会报错。

这是因为antdesignPro是JS项目吗？

**Comment by ascoders** [comment]
是 antd-pro 使用 react16 导致的，我已经升级兼容了，使用最新版就可以跑了：

![image](https://user-images.githubusercontent.com/7970947/33706499-53bdd10c-db6f-11e7-893e-47905e7fcc4b.png)

**Comment by tianqingfish** [comment]
谢谢黄神，如何使用最新版呀，还是直接npm安装就好了吗？

**Comment by ascoders** [comment]
不客气，直接 npm 安装就好了。

如果想了解具体实现细节可以另外开 issue，描述具体疑惑点。
