### ISSUE TITLE
发布的功能该怎么添加，保存好像没有效果

### ISSUE THREAD

**Issue by tianqingfish** [ascoders/gaea-editor#16]
1.我在AntPro中引用gaea之后，发现跟nextdesign中的gaea少了发布的功能。是有意而为之的嘛？

2.另外保存完后，保存的结果下次该如何读取？（next好像是通过发布版本，然后回滚版本实现的，这个gaea好像没发布这个功能）

3.我发现我进入别的页面，再返回gaea页面后，gaea组件会重复，如下图所示：

![image](https://user-images.githubusercontent.com/19572839/33938849-ec620ad0-e043-11e7-81e7-f0b21faa03e1.png)

以上三个问题还请黄神不吝指教。

**Comment by ascoders** [comment]
1. 发布功能不集成进来。有一个草稿概念，保存就是保存草稿，发布会将最新草稿拷贝一份固化存储，这个逻辑是纯后端的。
2. `<Editor value={}>` 将草稿，也就是 onSave 回调的返回值传给 value，就能读取结果了。
3. 这个应该是数据流重复初始化了，我看看怎么避免，你可以先通过给 Editor 不同的 key 强制销毁来解决？

**Comment by tianqingfish** [comment]
如果我最后想直接生成一个可执行的页面（也就是能够将我用gaea布局完的页面生成出来），后端那块有没有什么解决方案或者技术路线呢？您说个大概方向即可，我自己去学习。

PS：其实我的初衷是想把诸如Echart、G2这样的图表库导入到gaea中，然后允许通过拖拽来生成自定义布局图表页面。

**Comment by ascoders** [comment]
但是你的瓶颈在后端，学习一下 express、koa 之类的框架就行了。
