### ISSUE TITLE
请问能支持vue版本么，有兴趣参加^_^

### ISSUE THREAD

**Issue by CharlieLau** [ascoders/gaea-editor#17]

**Comment by ascoders** [comment]
为了保证功能同步更新，不建议再完全 copy 一遍。好在现在社区似乎有 react to vue 的轮子，可以试一试？

[vuera](https://github.com/akxcv/vuera)。

看上去挺简单的：

```vue
<template>
  <div>
    <gaea-editor />
  </div>
</template>

<script>
  import GaeaEditor from 'gaea-editor'

  export default {
    components: { 'gaea-editor': GaeaEditor },
  }
</script>
```

如果这个方案能跑起来，我把它写到文档里，作为对 vue 的支持方式。

**Comment by CharlieLau** [comment]
好 ，我也去试一下

**Comment by CharlieLau** [comment]
还有些许问题，添加自定义vue组件是不是还需要支持一下

**Comment by ascoders** [comment]
@CharlieLau 可以在 vue 跑起来吗？只是自定义 vue 组件还无法添加

**Comment by CharlieLau** [comment]
@ascoders  是支持的   我在我的仓库加了个 [demo](https://github.com/CharlieLau/gaea-editor-vue-demo)  
[online](https://charlielau.github.io/gaea-editor-vue-demo/index.html)

**Comment by CharlieLau** [comment]
我用vue实现了大部分功能，如果您同意，不日将上传。

**Comment by ascoders** [comment]
没问题，非常欢迎 👏。

**Comment by CharlieLau** [comment]
@ascoders  我用vue实现了第一版   https://github.com/CharlieLau/gaea-editor-vue

**Comment by ascoders** [comment]
真不可思议，非常棒！我把链接放到 readme 中，推荐给使用 vue 的开发者们。

你应该很了解这个编辑器了，后续不断开发插件即可。

**Comment by CharlieLau** [comment]
哈哈，我 拿到ali 的offer了，又可以和优秀的人共事了 @ascoders

**Comment by ascoders** [comment]
给力
