### ISSUE TITLE
【救急】antd-pro 引入报错

### ISSUE THREAD

**Issue by gebilaoman** [ascoders/gaea-editor#21]
### One-line summary [问题简述]

更新到antd-pro到最新版，引入gaea-editor，项目启动不起来。

### Version & Environment [版本及环境]
+ gaea-editor version [gaea-editor 版本]:2.1.8
+ Browser version [浏览器类型和版本]:chrome Version 66.0.3359.181
+ OS Version [操作系统类型和版本]:mac  10.13.4
+ Antd-Pro version [Antd-Pro  版本]:2.0.0-beta.1 // "react": "^16.2.0",

### Expected behaviour [期望结果]
官方代码跑起来，正常显示就好。我想只要官方demo可以跑，我的代码应该也没问题。

### gaea-editor code [gaea-editor代码]

```javascript
import Editor from 'gaea-editor';

render(){
    return  <Editor />
}

```

### Other comments [其他信息]

![image](https://user-images.githubusercontent.com/26354664/40913268-a39de042-6826-11e8-83c9-b6e14cdb2a7b.png)

**Comment by ascoders** [comment]
Please try `2.1.9`.

**Comment by gebilaoman** [comment]
Thanks, it works!!
