### ISSUE TITLE
关于中文界面和组件移除

### ISSUE THREAD

**Issue by weimin768** [ascoders/gaea-editor#23]
请问，界面文字可以切换为中文吗？
另外，当我添加了一个组件后，无法移除掉，请问现在是没有实现呢，还是有移除的方法，我没有找到？

**Comment by ascoders** [comment]
还没有实现移除功能，这周末有空的话我支持下

**Comment by ascoders** [comment]
暂时还不支持国际化，这个考虑支持中

**Comment by waybi** [comment]
@ascoders 为什么在jsfiddle上的demo显示的是中文

**Comment by ascoders** [comment]
目前最新版内置语言是英文，jsfiddle 上的 demo 比较老了。最近我会添加国际化的功能，支持中英文切换。

**Comment by ascoders** [comment]
@weimin768  @waybi `2.2.1` 添加了 `locale` 参数，支持 `zh` 与 `cn`

**Comment by waybi** [comment]
@ascoders ok 谢谢大神

**Comment by ascoders** [comment]
`2.2.2` 版本支持了组件实例的移除。
