### ISSUE TITLE
编辑器如何加上mobile模式

### ISSUE THREAD

**Issue by waybi** [ascoders/gaea-editor#24]
![image](https://user-images.githubusercontent.com/3403065/41399006-bd513206-6feb-11e8-8c7a-039914986eb7.png)
如图，这个效果需要自己实现的吗

**Comment by ascoders** [comment]
可以自己实现，这个插件没有移植过来

**Comment by ascoders** [comment]
@waybi 我周末看看～

**Comment by ascoders** [comment]
![image](https://user-images.githubusercontent.com/7970947/41528689-5408d9ea-731d-11e8-9301-dfa8d689e6b8.png)

Here you go. At `2.3.2`.

**Comment by waybi** [comment]
自定义组件报错 ：
![image](https://user-images.githubusercontent.com/3403065/41542658-039afa9e-7348-11e8-9478-bb34b3a13466.png)

```
<Editor
          componentClasses={[MyInput]}
        />
```
只要在编辑器Editor 加上这行componentClasses={[MyInput]}代码就会报上图错误
