### ISSUE TITLE
gaea-editor2.3.2版本 自定义组件报错 

### ISSUE THREAD

**Issue by waybi** [ascoders/gaea-editor#25]
![image](https://user-images.githubusercontent.com/3403065/41544620-c54715f8-734b-11e8-8b56-d621911c59a8.png)

```
<Editor
          componentClasses={[MyInput]}
        />
```
只要在编辑器Editor 加上这行componentClasses={[MyInput]}代码就会报上图错误

还有一个问题是 我git clone 项目到本地 无法跑起来，我是通过yarn 去install 跟这个有关系吗

**Comment by ascoders** [comment]
1. 本地使用 `npm run docs` 运行。
2. 自定义组件要定义 `editSetting`，参考 https://github.com/ascoders/gaea-basic-components/blob/master/src/container/type.ts
3. 必须至少有一个容器组件，建议 concat(gaeaBasicComponents)

**Comment by waybi** [comment]
@ascoders 谢谢 现在问题解决了
