### ISSUE TITLE
有点小疑问

### ISSUE THREAD

**Issue by janryWang** [ascoders/gaea-editor#3]
这个编辑器对于组件的设计要求应该不能是普遍适用的吧。
比如

```
<Select>
    <Option></Option>
</Select>

```

对于这种嵌套结构有限制的组件模式，编辑器应该不能在可视化编辑过程中组装出这样一个结构吧，如果应是要拖拽进去的话，因为每个组件都被高阶组件给封装了，按理说，也会影响组件的正常运行

**Comment by ascoders** [comment]
可以组装出这个结构，高阶组件封装不会产生多余的 dom 节点，属性都是透传的
