### ISSUE TITLE
display选择flex布局，预览的时候该属性丢失导致布局失效

### ISSUE THREAD

**Issue by qingqinxl1** [ascoders/gaea-editor#31]
> 选择flex布局

![flex布局](http://pe3w02ade.bkt.clouddn.com/WX20180827-141435.png)

> 预览效果

![预览](http://pe3w02ade.bkt.clouddn.com/WX20180827-141451.png)

**Comment by ascoders** [comment]
Reinstall `gaea-editor` or upgrade `gaea-render` to `1.0.23` will solve this problem.

**Comment by qingqinxl1** [comment]
It works well. Thanks!
