### ISSUE TITLE
这个怎么使用啊

### ISSUE THREAD

**Issue by jiujiude** [ascoders/gaea-editor#5]
这个怎么使用啊

**Comment by ascoders** [comment]
http://next.baidu.com/components/editor/gaea-editor/demo
点击右边，查看源码，照葫芦画瓢用，具体用法细节文档还没整理，这几天在重构核心模块

**Comment by ciiiii** [comment]
按照源码写的网页只有文本 布局这两个模块 是什么问题呢？

**Comment by ascoders** [comment]
新文档还没有添加，因为文本和布局是内置组件，其他组件需要用户自己添加。

```
<GaeaEditor componentClasses={[ CustomRC1, CustomRC2 ]}/>
```
