### ISSUE TITLE
Local development run,got a mistake

### ISSUE THREAD

**Issue by WeilongLiu001** [ascoders/gaea-editor#57]
I follow the steps Local development run.But go a mistake.
详细信息 
yarn run v1.9.4
$ pri docs
i  info      Lint and format code..
'tests)' 不是内部或外部命令，也不是可运行的程序

tslint不支持该写法？

**Comment by ascoders** [comment]
我能正常跑起来，node@10，命令：
```bash
npm install
npm run docs
```

你换成 npm 试试，或者重装下 node_modules？
