### ISSUE TITLE
请问这个可以获取到生成的JSX代码么

### ISSUE THREAD

**Issue by eddyzhang1986** [ascoders/gaea-editor#6]
请问这个可以获取到生成的JSX代码么，直接获取设计器生成的JSX代码，而不是那种JSON格式的描述？
这个支持吗，只需要正向获取到JSX即可，不需要反向从JSX生成界面，如果能直接拿到JSX代码的话这个设计器真的是太好了，大大提高了工作效率的说。

**Comment by ascoders** [comment]
把 `json` 解析一下就成 `jsx` 了，未来我可能会加上这个功能。

**Comment by eddyzhang1986** [comment]
@ascoders 
niubility,i am so worship you
崇拜中

**Comment by ascoders** [comment]
@eddyzhang1986 谈不上打杂，你可以把这个功能抽象出来，不一定要与编辑器耦合。

可以把编辑器生成的 json 当做语法树，可以通过给编辑器新增插件，或者自己写一个【通用语法树->jsx解析器】，我觉得做后者更有意义。

用什么模式都可以，总之做好了以后，通过 `decode` 拿到结构化数据，就可以解析了:

```javascript
import {decode} from 'gaea-editor'
const dataJson = decode(editorSaveData)
const jsxStr = yourParser(dataJson)
```

**Comment by ascoders** [comment]
继续 mark，这个功能蛮多人推荐的。

**Comment by nick121212** [comment]
@ascoders 你这个功能，我正好也在做，有没有联系方式沟通下

**Comment by nick121212** [comment]
这个是测试地址：https://nick121212.github.io/fx-schema-form-react-demo/dist/index.html#/panel/create

**Comment by theprimone** [comment]
> 把 `json` 解析一下就成 `jsx` 了，未来我可能会加上这个功能。

现在有下文了吗，如果纯用 `json` 渲染的话，UI 和数据的联动没法搞吧？

**Comment by ascoders** [comment]
@theprimone  json 语法有描述 UI 与数据联动 - 事件机制。

生成 jsx 还没做，因为我觉得可以根据 json 生成，大家生成的场景也不同，还是留给业务方自己做吧。

**Comment by theprimone** [comment]
@ascoders 现在我的难点是

1. 外部数据如何注入。当前的技术栈是 umi + dva + antd-mobile，也看了 [#12 中的回复](https://github.com/ascoders/gaea-editor/issues/12#issuecomment-318832673)，听你这么一说，是通过在渲染的时候将数据注入 json 配置中？
2. 事件机制没弄懂。看了 [#26 中的回复](https://github.com/ascoders/gaea-editor/issues/26#issuecomment-399654707)，现在能达到控制弹窗的效果了吗？

**Comment by ascoders** [comment]
1. 无论是通过插件把 json -> jsx 做成内置功能，还是外部 onChange 拿到 json 后手动转成 jsx 都可以，与技术方案没关系，只要是 react 体系即可。
2. 事件分为 trigger 和 action，trigger 可以是组件的回调比如 onClick，trigger 可以修改组件状态比如修改值为 visible，我看你做的比较深入，可以考虑 fork 一下看看源代码，发一个自己修改过源码的包使用。

**Comment by theprimone** [comment]
1. 我的想法是在组件中添加一个数据源的 `string` 字段，比如： `dataSource` 。渲染的时候遍历 `json` 根据 `dataSource` 为 `props` 注入组件渲染需要的数据。这样做的话就不用关心转换的问题了，纯展示型的页面应该没问题。
2. 添加事件没问题，但是触发另一个组件显示隐藏不行，选择触发事件，也没有可下拉的事件可供选择，不知道需要注意些什么。另，事件对象打印的是 `Proxy` 对象，序列化的话有问题，事件应该怎么序列化呢？以及如果让事件调用外部定义的方法呢？比如打开模态框的时候调用接口和点击确定调用查询接口。如果都能通过 `json` 解决就完美了

这就看看源码。

**Comment by theprimone** [comment]
之前的解决方案可行。给特定组件添加像 `dataSource` 和 `handleClick` 的字段，再在渲染时，根据对应的字段注入数据和方法即可。参考[feat: injectConfig to renderJson and save gaea-draft](https://github.com/theprimone/antd-mobile-editor/commit/c17e9dafb10adea773b4cfab82fd8176118e5a2f)。不知道这样的解决方案如何？

另，很尴尬，源码 `npm i` 后启动报错

```
Analyse project×  fatal     Unexpected file or directory: D:\workspaces\github\gaea-editor\node_modules\.bin
```

这是在我删了之前两次文件后的报错，真是疑惑。

**Comment by ascoders** [comment]
目前不支持 windows 系统调试源码，能试试 linux 环境吗

**Comment by theprimone** [comment]
有点硬核了，用 gitpod 打开了 😆

**Comment by theprimone** [comment]
搞了个可配置的属性，大佬看看可以合并不？ 单独发布好像没太大必要。

[feat: config layout of editor](https://github.com/ascoders/gaea-editor/pull/67)

**Comment by ascoders** [comment]
功能截图有吗

**Comment by theprimone** [comment]
在 `src/gaea-editor.type.tsx` 加了配置

```ts
/**
 * Editor layout
 */
public layout?: {
  showDragMenu: boolean;
  defaultViewMode: ViewMode;
} = { showDragMenu: false, defaultViewMode: 'PC' };
```

当我这样初始化配置的时候

```tsx
<Editor layout={{ showDragMenu: true, defaultViewMode: 'Iphone6/7/8' } { ...rest } />
```

就达到初始化布局的目的了，后续可扩展配置。

==================================

另，我试了异步为 `gaea-render` 赋值，发现渲染器不会刷新 UI ，这该怎么办呢？试了试用 `ref` 再 `forceUpdate()` 也不行，最后一步了，我太难了 \_(:3J∠)\_

**Comment by theprimone** [comment]
看了看 `gaea-render` 的源码，重写了一个渲染组件解决了 [`gaea-injection-render`](https://github.com/theprimone/gaea-injection-render) 不能刷新的问题

终于跑完整个流程了 \_(:3J∠)\_
