### ISSUE TITLE
[BUG] 当属性过多的时候,无法点击到对应的添加事件的按钮

### ISSUE THREAD

**Issue by jhoneybee** [ascoders/gaea-editor#61]
## 开发环境

|环境     |  版本
|-----      |--------
|Window |  win10 1083
|Debian子系统 | Linux DESKTOP-DBQL52F 4.4.0-17134-Microsoft #706-Microsoft Mon Apr 01 18:13:00 PST 2019 x86_64 GNU/Linux
|nodejs   | v12.4.0 
|npm      | 6.9.0 
| Google Chrome         |  75.0.3770.100（正式版本） （64 位）
| gaea-editor    | 2.3.24

## 复现地址
![image](https://user-images.githubusercontent.com/24241052/60311175-adae6400-9988-11e9-9a7b-9be1d6ceb3a3.png)

+ https://gaeajs.github.io/gaea-site/ 

> 拖拽一个按钮,然后进行事件的编辑的时候发现无法正常查看或者点击

## 最小化仓库地址

+ https://github.com/ascoders/gaea-editor.git

## 期望结果 

可以通过滚动的方式,操作属性比较多的控件

**Comment by joebnb** [comment]
随便找个地方 给 ant tabs 添加scroll 样式
```css
.main-tool-container .ant-tabs{
    overflow:scroll;
}
```
