### ISSUE TITLE
window安装了包之后,启动

### ISSUE THREAD

**Issue by liangshaoqi** [ascoders/gaea-editor#63]
![image](https://user-images.githubusercontent.com/31196617/63326332-9a06f480-c35e-11e9-8fbd-53e4b8ce389b.png)
![image](https://user-images.githubusercontent.com/31196617/63326345-a12e0280-c35e-11e9-9064-b231983f70c7.png)

**Comment by liangshaoqi** [comment]
怎么能忽略掉你那个mac才有的包

**Comment by ascoders** [comment]
目前不支持 window 系统

**Comment by liangshaoqi** [comment]
好的,谢谢
