### ISSUE TITLE
npm run docs运行不起来

### ISSUE THREAD

**Issue by jerryjiao** [ascoders/gaea-editor#64]
Node版本：9.0.0

使用了wsl在windows 环境中

install之后报错：

![企业微信截图_20190828183814](https://user-images.githubusercontent.com/12718716/63848736-05863d00-c9c3-11e9-9fa7-c84b652bbbbb.png)

试着重装也不行。。

**Comment by ascoders** [comment]
源码不支持 windows 调试，但 `gaea-editor` npm 包支持 windows

**Comment by jerryjiao** [comment]
> 源码不支持 windows 调试，但 `gaea-editor` npm 包支持 windows

呃，大佬，我是尝试用了issue里那个装Linux子系统的教程，可能还是不行吧
