### ISSUE TITLE
引入Editor报错，Xe.create is not a function

### ISSUE THREAD

**Issue by jerryjiao** [ascoders/gaea-editor#65]
node: 9.11.2
npm : 6.11.3
"gaea-editor": "2.3.24",
"react": "16.8.6",
"react-dom": "16.8.6"

代码：
```
import React from "react";
import ReactDOM from "react-dom";
import Editor from 'gaea-editor'

import "./styles.css";

function App() {
  return (
    <div className="App">
      <Editor />
    </div>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

大佬，我就这样引入了一下，然后跑起来报这个错：
![企业微信截图_15692187324792](https://user-images.githubusercontent.com/12718716/65404717-4af42980-de0c-11e9-848a-20c98fa317d8.png)

**Comment by theprimone** [comment]
\_(:3J∠)\_ 同样的错。。。楼主解决了吗？

**Comment by ascoders** [comment]
正在修复

**Comment by ascoders** [comment]
发布了 `gaea-editor@2.3.26` 解决了这个问题

**Comment by theprimone** [comment]
成了，非常感谢 :+1:

**Comment by jerryjiao** [comment]
感谢感谢！
