### ISSUE TITLE
如何初始化编辑器布局？

### ISSUE THREAD

**Issue by theprimone** [ascoders/gaea-editor#66]
确实很强大，但是文档太少了，看来看去都不知道怎么初始化布局，每次刷新页面都得手动重设一边，好烦躁 \_(:3J∠)\_

现在想达到的效果是默认打开左侧组件栏和默认 Iphone6/7/8 的视图

**Comment by ascoders** [comment]
不支持外部控制，这些是内部状态，如果想深度定制就要 fork 代码改源码啦。

**Comment by theprimone** [comment]
这么硬核的吗？:laughing:

那我还是先研究组件吧
