### ISSUE TITLE
引用webBaseComponents 时 报 BUG [mobx] Deprecated

### ISSUE THREAD

**Issue by eddyzhang1986** [ascoders/gaea-editor#7]
[mobx] Deprecated: 
In MobX 2.* passing a function without arguments to (extend)observable will automatically be inferred to be a computed value.
This behavior is ambiguous and will change in MobX 3 to create just an observable reference to the value passed in.
To disambiguate, please pass the function wrapped with a modifier: use 'co
![qq 20170214111342](https://cloud.githubusercontent.com/assets/6470398/22913585/af7da312-f2a6-11e6-9b65-a469a1468fe4.png)
mputed(fn)' (for current behavior; automatic conversion), or 'asReference(fn)' (future behavior, just store reference) or 'action(fn)'.
Note that the idiomatic way to write computed properties is 'observable({ get propertyName() { ... }})'.
For more details, see https://github.com/mobxjs/mobx/issues/532)in: ObservableObject@42.onClick

**Comment by eddyzhang1986** [comment]
这个功能应该是mobx更新引起的 虽然仅仅是警告 不过对于我这种有代码洁癖的人...

**Comment by ascoders** [comment]
这段时间我在用redux重构

**Comment by eddyzhang1986** [comment]
@ascoders  欧克 thx

**Comment by ascoders** [comment]
过段时间还是准备用 https://github.com/ascoders/dynamic-object 重构，这个是 mobx 的加强版，用了 proxy。

**Comment by ascoders** [comment]
已重写
